services:
  zk1:
    container_name: zk1
    hostname: zk1
    image: bitnami/zookeeper:3.6.2
    ports:
      - 21811:2181 # port map from container to host
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=1
      - ZOO_SERVERS=0.0.0.0:2888:3888,zk2:2888:3888,zk3:2888:3888,z4:2888:3888,zk5:2888:3888,zk6:2888:3888,z7:2888:3888,zk8:2888:3888,zk9:2888:3888 # ports for internal communication, P2P comms and leader election ensemble
  zk2:
    container_name: zk2
    hostname: zk2
    image: bitnami/zookeeper:3.6.2
    ports:
      - 21812:2181 # port map from container to host
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=2
      - ZOO_SERVERS=zk1:2888:3888,0.0.0.0:2888:3888,zk3:2888:3888,z4:2888:3888,zk5:2888:3888,zk6:2888:3888,z7:2888:3888,zk8:2888:3888,zk9:2888:3888 # ports for internal communication, P2P comms and leader election ensemble
  zk3:
    container_name: zk3
    hostname: zk3
    image: bitnami/zookeeper:3.6.2
    ports:
      - 21813:2181 # port map from container to host
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOO_SERVER_ID=3
      - ZOO_SERVERS=zk1:2888:3888,zk2:2888:3888,0.0.0.0:2888:3888,z4:2888:3888,zk5:2888:3888,zk6:2888:3888,z7:2888:3888,zk8:2888:3888,zk9:2888:3888 # ports for internal communication, P2P comms and leader election ensemble
  # zk4:
  #   container_name: zk4
  #   hostname: zk4
  #   image: bitnami/zookeeper:3.6.2
  #   ports:
  #     - 21814:2181 # port map from container to host
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  #     - ZOO_SERVER_ID=4
  #     - ZOO_SERVERS=z1:2888:3888,zk2:2888:3888,zk3:2888:3888,0.0.0.0:2888:3888,zk5:2888:3888,zk6:2888:3888,z7:2888:3888,zk8:2888:3888,zk9:2888:3888 # ports for internal communication, P2P comms and leader election ensemble
  # zk5:
  #   container_name: zk5
  #   hostname: zk5
  #   image: bitnami/zookeeper:3.6.2
  #   ports:
  #     - 21815:2181 # port map from container to host
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  #     - ZOO_SERVER_ID=5
  #     - ZOO_SERVERS=zk1:2888:3888,zk2:2888:3888,zk3:2888:3888,z4:2888:3888,0.0.0.0:2888:3888,zk6:2888:3888,z7:2888:3888,zk8:2888:3888,zk9:2888:3888 # ports for internal communication, P2P comms and leader election ensemble
  # zk6:
  #   container_name: zk6
  #   hostname: zk6
  #   image: bitnami/zookeeper:3.6.2
  #   ports:
  #     - 21816:2181 # port map from container to host
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  #     - ZOO_SERVER_ID=6
  #     - ZOO_SERVERS=zk1:2888:3888,zk2:2888:3888,z3:2888:3888,z4:2888:3888,zk5:2888:3888,0.0.0.0:2888:3888,z7:2888:3888,zk8:2888:3888,zk9:2888:3888 # ports for internal communication, P2P comms and leader election ensemble
  # zk7:
  #   container_name: zk7
  #   hostname: zk7
  #   image: bitnami/zookeeper:3.6.2
  #   ports:
  #     - 21817:2181 # port map from container to host
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  #     - ZOO_SERVER_ID=7
  #     - ZOO_SERVERS=z1:2888:3888,zk2:2888:3888,zk3:2888:3888,z4:2888:3888,zk5:2888:3888,zk6:2888:3888,0.0.0.0:2888:3888,zk8:2888:3888,zk9:2888:3888 # ports for internal communication, P2P comms and leader election ensemble
  # zk8:
  #   container_name: zk8
  #   hostname: zk8
  #   image: bitnami/zookeeper:3.6.2
  #   ports:
  #     - 21818:2181 # port map from container to host
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  #     - ZOO_SERVER_ID=8
  #     - ZOO_SERVERS=zk1:2888:3888,z2:2888:3888,zk3:2888:3888,z4:2888:3888,zk5:2888:3888,zk6:2888:3888,z7:2888:3888,0.0.0.0:2888:3888,zk9:2888:3888 # ports for internal communication, P2P comms and leader election ensemble
  # zk9:
  #   container_name: zk9
  #   hostname: zk9
  #   image: bitnami/zookeeper:3.6.2
  #   ports:
  #     - 21819:2181 # port map from container to host
  #   environment:
  #     - ALLOW_ANONYMOUS_LOGIN=yes
  #     - ZOO_SERVER_ID=9
  #     - ZOO_SERVERS=zk1:2888:3888,zk2:2888:3888,z3:2888:3888,z4:2888:3888,zk5:2888:3888,zk6:2888:3888,z7:2888:3888,zk8:2888:3888,0.0.0.0:2888:3888 # ports for internal communication, P2P comms and leader election ensemble
  zoonavigator:
    container_name: zoonavigator
    image: elkozmon/zoonavigator
    ports:
      - 9000:9000 # port map from container to host